=== Giang94/fu-se605-advantage-xml/XML_Phase_4/WebContent/northwind.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="categories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" type="category" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="suppliers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="supplier" type="supplier" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" type="product" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" fixed="northwind" />
        </xs:complexType>
    </xs:element>
                
    <xs:complexType name="category">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="CategoryID" type="xs:integer" nillable="false"/>
            <xs:element name="CategoryName" nillable="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Description" type="xs:string"  nillable="true"/>
            <xs:element name="Picture" type="picture"  nillable="true"/>
            <xs:element name="File" type="xs:string"  nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="supplier">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="SupplierID" type="xs:integer"  nillable="false"/>
            <xs:element name="CompanyName"  nillable="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="40"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="ContactName"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="30"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="ContactTitle"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="30"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Address"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="City"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Region"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="PostalCode"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Country"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Phone"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="24"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="Fax"  nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="24"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="HomePage" type="xs:string"  nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="product">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="ProductID" type="xs:integer" nillable="false"/>
            <xs:element name="ProductName" nillable="false">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="40"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="SupplierID" type="xs:integer" nillable="true"/>
            <xs:element name="CategoryID" type="xs:integer" nillable="true"/>
            <xs:element name="QuantityPerUnit" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="UnitPrice" nillable="true" default="0.00">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="12" />
						<xs:fractionDigits value="2" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
            <xs:element name="UnitsInStock" type="smallint" nillable="true" default="0"/>
            <xs:element name="UnitsOnOrder" type="smallint" nillable="true" default="0"/>
            <xs:element name="ReorderLevel" type="smallint" nillable="true" default="0"/>
            <xs:element name="Discontinued" type="discontinued" nillable="false" default="0"/>
        </xs:sequence>
    </xs:complexType>
	
	
	<xs:simpleType name='smallint'>
		<xs:restriction base='xs:integer'>
			<xs:minInclusive value='-32768'/>
			<xs:maxInclusive value='32767'/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name='discontinued'>
		<xs:restriction base='xs:integer'>
			<xs:enumeration value='0'/>
			<xs:enumeration value='1'/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="picture">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-1]*"/>
			<xs:minLength value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== Giang94/fu-se605-advantage-xml/XML_Phase_3/northwind.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="northwind.xsl"?>
<database name="northwind"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="northwind.xsd"> 
	<!-- Table categories -->
	<categories>
		<category>
			<CategoryID>1</CategoryID> 
			<CategoryName>Beverages</CategoryName>
			<Description>Beers, ales and other drinks </Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>2</CategoryID>
			<CategoryName>Condiments</CategoryName>
			<Description>Sweet and savory sauces,&amp;nbsp;relishes, spreads, and seasonings</Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>3</CategoryID>
			<CategoryName>Confections</CategoryName>
			<Description>Desserts, candies, and sweet breads </Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>4</CategoryID>
			<CategoryName>Dairy Products</CategoryName>
			<Description>Cheeses</Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>5</CategoryID>
			<CategoryName>Grains/Cereals</CategoryName>
			<Description>Breads, crackers, pasta, and cereal</Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>6</CategoryID>
			<CategoryName>Meat/Poultry</CategoryName>
			<Description>Prepared meats</Description>
			<Picture></Picture>
			<File>NULL</File>
		</category>
		<category>
			<CategoryID>7</CategoryID>
			<CategoryName>Produce</CategoryName>
			<Description>NULL</Description>
			<Picture></Picture>
			<File>NULL</File>
		</category>
		<category>
			<CategoryID>8</CategoryID>
			<CategoryName>Seafood</CategoryName>
			<Description>Seaweed and fish</Description>
			<Picture></Picture>
			<File></File>
		</category>
		<category>
			<CategoryID>225</CategoryID>
			<CategoryName>cake and pastry</CategoryName>
			<Description>wedding cakes, pastry, fancy cakes, sponge-cakes</Description>
			<Picture></Picture>
			<File>cake and pastry.doc</File>
		</category>
	</categories>
	<!-- Table suppliers -->
	<suppliers>
		<supplier>
			<SupplierID>1</SupplierID>
			<CompanyName>Exotic Liquids</CompanyName>
			<ContactName>Charlotte Cooper</ContactName>
			<ContactTitle>Purchasing Manager</ContactTitle>
			<Address>49 Gilbert St.</Address>
			<City>London</City>
			<Region></Region>
			<PostalCode>EC1 4SD</PostalCode>
			<Country>UK</Country>
			<Phone>(171) 555-2222</Phone>
			<Fax></Fax>
			<HomePage>Exotic.com</HomePage>
		</supplier>
		<supplier>
			<SupplierID>2</SupplierID>
			<CompanyName>New Orleans Cajun Delights</CompanyName>
			<ContactName>Shelley Burke</ContactName>
			<ContactTitle>Order Administrator</ContactTitle>
			<Address>P.O. Box 78934</Address>
			<City>New Orleans</City>
			<Region>LA</Region>
			<PostalCode>70117</PostalCode>
			<Country>USA</Country>
			<Phone>(100) 555-4822</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>3</SupplierID>
			<CompanyName>Grandma Kelly's Homestead</CompanyName>
			<ContactName>Regina Murphy</ContactName>
			<ContactTitle>Sales Representative</ContactTitle>
			<Address>707 Oxford Rd.</Address>
			<City>Ann Arbor</City>
			<Region>MI</Region>
			<PostalCode>48104</PostalCode>
			<Country>USA</Country>
			<Phone>(313) 555-5735</Phone>
			<Fax>(313) 555-3349</Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>4</SupplierID>
			<CompanyName>Tokyo Traders</CompanyName>
			<ContactName>Yoshi Nagase</ContactName>
			<ContactTitle>Marketing Manager</ContactTitle>
			<Address>9-8 Sekimai
				Musashino-shi</Address>
			<City>Tokyo</City>
			<Region></Region>
			<PostalCode>100</PostalCode>
			<Country>Japan</Country>
			<Phone>(03) 3555-5011</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>5</SupplierID>
			<CompanyName>Cooperativa de Quesos 'Las Cabras'</CompanyName>
			<ContactName>Antonio del Valle Saavedra</ContactName>
			<ContactTitle>Export Administrator</ContactTitle>
			<Address>Calle del Rosal 4</Address>
			<City>Oviedo</City>
			<Region>Asturias</Region>
			<PostalCode>33007</PostalCode>
			<Country>Spain</Country>
			<Phone>(98) 598 76 54</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>6</SupplierID>
			<CompanyName>Mayumi's</CompanyName>
			<ContactName>Mayumi Ohno</ContactName>
			<ContactTitle>Marketing Representative</ContactTitle>
			<Address>92 SetsukoChuo-ku</Address>
			<City>Osaka</City>
			<Region></Region>
			<PostalCode>545</PostalCode>
			<Country>Japan</Country>
			<Phone>(06) 431-7877</Phone>
			<Fax></Fax>
			<HomePage>ya.ru</HomePage>
		</supplier>
		<supplier>
			<SupplierID>7</SupplierID>
			<CompanyName>Pavlova, Ltd.</CompanyName>
			<ContactName>Ian Devling</ContactName>
			<ContactTitle>Marketing Manager</ContactTitle>
			<Address>74 Rose St.
				Moonie Ponds</Address>
			<City>Melbourne</City>
			<Region>Victoria</Region>
			<PostalCode>3058</PostalCode>
			<Country>Australia</Country>
			<Phone>(03) 444-2343</Phone>
			<Fax>(03) 444-6588</Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>8</SupplierID>
			<CompanyName>Specialty Biscuits, Ltd.</CompanyName>
			<ContactName>Peter Wilson</ContactName>
			<ContactTitle>Sales Representative</ContactTitle>
			<Address>29 King's Way</Address>
			<City>Manchester</City>
			<Region></Region>
			<PostalCode>M14 GSD</PostalCode>
			<Country>UK</Country>
			<Phone>(161) 555-4448</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>9</SupplierID>
			<CompanyName>PB Knackebrod AB</CompanyName>
			<ContactName>Lars Peterson</ContactName>
			<ContactTitle>Sales Agent</ContactTitle>
			<Address>Kaloadagatan 13</Address>
			<City>Goteborg</City>
			<Region></Region>
			<PostalCode>S-345 67</PostalCode>
			<Country>Sweden</Country>
			<Phone>031-987 65 43</Phone>
			<Fax>031-987 65 91</Fax>
			<HomePage>yahoo.com</HomePage>
		</supplier>
		<supplier>
			<SupplierID>10</SupplierID>
			<CompanyName>Refrescos Americanas LTDA</CompanyName>
			<ContactName>Carlos Diaz</ContactName>
			<ContactTitle>Marketing Manager</ContactTitle>
			<Address>Av. das Americanas 12.890</Address>
			<City>Sao Paulo</City>
			<Region></Region>
			<PostalCode>5442</PostalCode>
			<Country>Brazil</Country>
			<Phone>(11) 555 4640</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>11</SupplierID>
			<CompanyName>Heli Su?waren GmbH &amp; Co. KG</CompanyName>
			<ContactName>Petra Winkler</ContactName>
			<ContactTitle>Sales Manager</ContactTitle>
			<Address>Tiergartenstra?e 5</Address>
			<City>Berlin</City>
			<Region></Region>
			<PostalCode>10785</PostalCode>
			<Country>Germany</Country>
			<Phone>(010) 9984510</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>12</SupplierID>
			<CompanyName>Plutzer Lebensmittelgro?markte AG</CompanyName>
			<ContactName>Martin Bein</ContactName>
			<ContactTitle>International Marketing Mgr.</ContactTitle>
			<Address>Bogenallee 51</Address>
			<City>Frankfurt</City>
			<Region></Region>
			<PostalCode>60439</PostalCode>
			<Country>Germany</Country>
			<Phone>(069) 992755</Phone>
			<Fax></Fax>
			<HomePage>microsoft.com</HomePage>
		</supplier>
		<supplier>
			<SupplierID>13</SupplierID>
			<CompanyName>Nord-Ost-Fisch Handelsgesellschaft mbH</CompanyName>
			<ContactName>Sven Petersen</ContactName>
			<ContactTitle>Coordinator Foreign Markets</ContactTitle>
			<Address>Frahmredder 112a</Address>
			<City>Cuxhaven</City>
			<Region></Region>
			<PostalCode>27478</PostalCode>
			<Country>Germany</Country>
			<Phone>(04721) 8713</Phone>
			<Fax>(04721) 8714</Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>14</SupplierID>
			<CompanyName>Formaggi Fortini s.r.l.</CompanyName>
			<ContactName>Elio Rossi</ContactName>
			<ContactTitle>Sales Representative</ContactTitle>
			<Address>Viale Dante, 75</Address>
			<City>Ravenna</City>
			<Region></Region>
			<PostalCode>48100</PostalCode>
			<Country>Italy</Country>
			<Phone>(0544) 60323</Phone>
			<Fax>(0544) 60603</Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>15</SupplierID>
			<CompanyName>Norske Meierier</CompanyName>
			<ContactName>Beate Vileid</ContactName>
			<ContactTitle>Marketing Manager</ContactTitle>
			<Address>Hatlevegen 5</Address>
			<City>Sandvika</City>
			<Region></Region>
			<PostalCode>1320</PostalCode>
			<Country>Norway</Country>
			<Phone>(0)2-953010</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>16</SupplierID>
			<CompanyName>Bigfoot Breweries</CompanyName>
			<ContactName>Cheryl Saylor</ContactName>
			<ContactTitle>Regional Account Rep.</ContactTitle>
			<Address>3400 - 8th Avenue
				Suite 210</Address>
			<City>Bend</City>
			<Region>OR</Region>
			<PostalCode>97101</PostalCode>
			<Country>USA</Country>
			<Phone>(503) 555-9931</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>17</SupplierID>
			<CompanyName>Svensk Sjofoda AB</CompanyName>
			<ContactName>Michael Bjorn</ContactName>
			<ContactTitle>Sales Representative</ContactTitle>
			<Address>Brovallavagen 231</Address>
			<City>Stockholm</City>
			<Region></Region>
			<PostalCode>S-123 45</PostalCode>
			<Country>Sweden</Country>
			<Phone>08-123 45 67</Phone>
			<Fax></Fax>
			<HomePage>NULL</HomePage>
		</supplier>
		<supplier>
			<SupplierID>18</SupplierID>
			<CompanyName>Aux joyeux ecclesiastiques</CompanyName>
			<ContactName>Guylene Nodier</ContactName>
			<ContactTitle>Sales Manager</ContactTitle>
			<Address>203, Rue des Francs-Bourgeois</Address>
			<City>Paris</City>
			<Region></Region>
			<PostalCode>75004</PostalCode>
			<Country>France</Country>
			<Phone>(1) 03.83.00.68</Phone>
